### ISSUE TITLE
BadJpqlGrammarException: No viable alternative at input 

### ISSUE THREAD

**Issue by inverseTrig** [line/kotlin-jdsl#736]
안녕하세요, 아래와 같이 주어진 Author ID 와 연관관계가 없는 Book 목록을 조회하고자 합니다. 주어진 작가 ID 목록이 복수일때 (아래 `test_multiple_filter` 테스트 예시) 는 정상동작하지만 주어진 작가 ID 목록이 한개일때 아래와 같은 오류가 발생합니다 (아래 `test_filter` 테스트 예시). 

`test_filter` 와 `test_multiple_filter` 의 차이점은 아래와 같습니다. (맨 아래 테스트 코드 전체가 있습니다.)

```kotlin
// test_filter
val actual = bookRepository.getBooksByRuleset(
    ruleset = Ruleset(
        allSubRulesets = listOf(SubRuleset(listOf(author1.id)))
    ),
    pageable = pageable,
)

// test_multiple_filter
val actual = bookRepository.getBooksByRuleset(
            ruleset = Ruleset(
                allSubRulesets = listOf(
                    SubRuleset(listOf(author1.id)),
                    SubRuleset(listOf(author3.id)),
                ),
            ),
            pageable = pageable,
        )
```

# 현상
```
org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:229 no viable alternative at input 'NOT(EXISTS(SELECTAuthorBookAssociationFROMAuthorBookAssociationASAuthorBookAssociationWHERE(AuthorBookAssociation.author.idIN(:param1))AND(AuthorBookAssociation.book.id=Book.id)))'; Bad JPQL grammar [SELECT Book FROM Book AS Book WHERE NOT(EXISTS (SELECT AuthorBookAssociation FROM AuthorBookAssociation AS AuthorBookAssociation WHERE (AuthorBookAssociation.author.id IN (:param1)) AND (AuthorBookAssociation.book.id = Book.id)))]
org.springframework.dao.InvalidDataAccessApiUsageException: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:229 no viable alternative at input 'NOT(EXISTS(SELECTAuthorBookAssociationFROMAuthorBookAssociationASAuthorBookAssociationWHERE(AuthorBookAssociation.author.idIN(:param1))AND(AuthorBookAssociation.book.id=Book.id)))'; Bad JPQL grammar [SELECT Book FROM Book AS Book WHERE NOT(EXISTS (SELECT AuthorBookAssociation FROM AuthorBookAssociation AS AuthorBookAssociation WHERE (AuthorBookAssociation.author.id IN (:param1)) AND (AuthorBookAssociation.book.id = Book.id)))]
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:371)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:246)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:335)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:160)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:165)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
	at jdk.proxy3/jdk.proxy3.$Proxy119.getBooksByRuleset(Unknown Source)
	at com.example.demo.BookRepositoryTest.test_filter(BookRepositoryTest.kt:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalArgumentException: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:229 no viable alternative at input 'NOT(EXISTS(SELECTAuthorBookAssociationFROMAuthorBookAssociationASAuthorBookAssociationWHERE(AuthorBookAssociation.author.idIN(:param1))AND(AuthorBookAssociation.book.id=Book.id)))'; Bad JPQL grammar [SELECT Book FROM Book AS Book WHERE NOT(EXISTS (SELECT AuthorBookAssociation FROM AuthorBookAssociation AS AuthorBookAssociation WHERE (AuthorBookAssociation.author.id IN (:param1)) AND (AuthorBookAssociation.book.id = Book.id)))]
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport.renderSortedQuery(JpaQueryParserSupport.java:56)
	at org.springframework.data.jpa.repository.query.JpaQueryEnhancer.applySorting(JpaQueryEnhancer.java:103)
	at com.linecorp.kotlinjdsl.support.spring.data.jpa.JpqlEntityManagerUtils.createEnhancedQuery(JpqlEntityManagerUtils.kt:71)
	at com.linecorp.kotlinjdsl.support.spring.data.jpa.repository.KotlinJdslJpqlExecutorImpl.createJpaEnhancedQuery(KotlinJdslJpqlExecutorImpl.kt:222)
	at com.linecorp.kotlinjdsl.support.spring.data.jpa.repository.KotlinJdslJpqlExecutorImpl.createPage(KotlinJdslJpqlExecutorImpl.kt:285)
	at com.linecorp.kotlinjdsl.support.spring.data.jpa.repository.KotlinJdslJpqlExecutorImpl.findPage(KotlinJdslJpqlExecutorImpl.kt:108)
	at com.linecorp.kotlinjdsl.support.spring.data.jpa.repository.KotlinJdslJpqlExecutorImpl.findPage(KotlinJdslJpqlExecutorImpl.kt:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at com.linecorp.kotlinjdsl.support.spring.data.jpa.repository.KotlinJdslJpqlExecutorImpl$$SpringCGLIB$$0.findPage(<generated>)
	at com.example.demo.CustomBookRepositoryImpl.getBooksByRuleset(BookRepository.kt:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:277)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	... 13 more
Caused by: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:229 no viable alternative at input 'NOT(EXISTS(SELECTAuthorBookAssociationFROMAuthorBookAssociationASAuthorBookAssociationWHERE(AuthorBookAssociation.author.idIN(:param1))AND(AuthorBookAssociation.book.id=Book.id)))'; Bad JPQL grammar [SELECT Book FROM Book AS Book WHERE NOT(EXISTS (SELECT AuthorBookAssociation FROM AuthorBookAssociation AS AuthorBookAssociation WHERE (AuthorBookAssociation.author.id IN (:param1)) AND (AuthorBookAssociation.book.id = Book.id)))]
	at org.springframework.data.jpa.repository.query.BadJpqlGrammarErrorListener.syntaxError(BadJpqlGrammarErrorListener.java:39)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at org.springframework.data.jpa.repository.query.HqlParser.dealingWithNullExpression(HqlParser.java:9363)
	at org.springframework.data.jpa.repository.query.HqlParser.predicate(HqlParser.java:8945)
	at org.springframework.data.jpa.repository.query.HqlParser.whereClause(HqlParser.java:3657)
	at org.springframework.data.jpa.repository.query.HqlParser.query(HqlParser.java:1227)
	at org.springframework.data.jpa.repository.query.HqlParser.orderedQuery(HqlParser.java:1081)
	at org.springframework.data.jpa.repository.query.HqlParser.queryExpression(HqlParser.java:459)
	at org.springframework.data.jpa.repository.query.HqlParser.selectStatement(HqlParser.java:391)
	at org.springframework.data.jpa.repository.query.HqlParser.ql_statement(HqlParser.java:321)
	at org.springframework.data.jpa.repository.query.HqlParser.start(HqlParser.java:258)
	at org.springframework.data.jpa.repository.query.HqlQueryParser.parseQuery(HqlQueryParser.java:53)
	at org.springframework.data.jpa.repository.query.HqlQueryParser.parse(HqlQueryParser.java:63)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.lambda$0(JpaQueryParserSupport.java:182)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:135)
	at org.springframework.data.util.Lazy.get(Lazy.java:113)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.getContext(JpaQueryParserSupport.java:194)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport.renderSortedQuery(JpaQueryParserSupport.java:54)
	... 57 more
```

## `DemoApplication.kt`

```kotlin
@SpringBootApplication
@EnableJpaRepositories
class DemoApplication

fun main(args: Array<String>) {
	runApplication<DemoApplication>(*args)
}

@Entity
class Book(
	@Column(nullable = false)
	val name: String,
) {
	@Id
	val id: UUID = UUID.randomUUID()
}

@Entity
class Author(
	@Column(nullable = false)
	val name: String,
) {
	@Id
	val id: UUID = UUID.randomUUID()
}

@Entity
class AuthorBookAssociation(
	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "author_id", nullable = false)
	val author: Author,

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "book_id", nullable = false)
	val book: Book,
) {
	@Id
	val id: UUID = UUID.randomUUID()
}
```

## `BookRepository.kt`

```kotlin
interface BookRepository : JpaRepository<Book, UUID>, CustomBookRepository

interface CustomBookRepository {
    fun getBooksByRuleset(
        ruleset: Ruleset, pageable: Pageable,
    ): Page<Book?>
}

class CustomBookRepositoryImpl(
    private val kotlinJdslJpqlExecutor: KotlinJdslJpqlExecutor,
) : CustomBookRepository {
    override fun getBooksByRuleset(ruleset: Ruleset, pageable: Pageable): Page<Book?> {
        return kotlinJdslJpqlExecutor.findPage(pageable) {
            select(entity(Book::class))
                .from(entity(Book::class))
                .where(
                    not(
                        and(
                            *ruleset.allSubRulesets
                                .map { subRuleset ->
                                    exists(
                                        select(entity(AuthorBookAssociation::class))
                                            .from(entity(AuthorBookAssociation::class))
                                            .whereAnd(
                                                path(AuthorBookAssociation::author).path(Author::id)
                                                    .`in`(subRuleset.anyIds),
                                                path(AuthorBookAssociation::book).path(Book::id).eq(path(Book::id)),
                                            ).asSubquery(),
                                    )
                                }.toTypedArray(),
                        )
                    )
                )
        }
    }
}

data class Ruleset(
    val allSubRulesets: List<SubRuleset>,
)

data class SubRuleset(
    val anyIds: List<UUID>,
)
```

## `BookRepositoryTest.kt`

```kotlin
@DataJpaTest(showSql = true)
@Import(KotlinJdslAutoConfiguration::class)
class BookRepositoryTest {

    @Autowired
    private lateinit var testEntityManager: TestEntityManager

    @Autowired
    private lateinit var bookRepository: BookRepository

    // This test fails
    @Test
    fun test_filter() {
        val book1 = Book("Book1")
        val book2 = Book("Book2")
        val book3 = Book("Book3")

        val author1 = Author("Author1")
        val author2 = Author("Author2")
        val author3 = Author("Author3")
        val author4 = Author("Author4")
        val author5 = Author("Author5")

        val association1 = AuthorBookAssociation(author1, book1)
        val association2 = AuthorBookAssociation(author2, book1)

        val association3 = AuthorBookAssociation(author1, book2)
        val association4 = AuthorBookAssociation(author3, book2)

        val association5 = AuthorBookAssociation(author3, book3)
        val association6 = AuthorBookAssociation(author4, book3)
        val association7 = AuthorBookAssociation(author5, book3)

        testEntityManager.persist(book1)
        testEntityManager.persist(book2)
        testEntityManager.persist(book3)
        testEntityManager.persist(author1)
        testEntityManager.persist(author2)
        testEntityManager.persist(author3)
        testEntityManager.persist(author4)
        testEntityManager.persist(author5)
        testEntityManager.persist(association1)
        testEntityManager.persist(association2)
        testEntityManager.persist(association3)
        testEntityManager.persist(association4)
        testEntityManager.persist(association5)
        testEntityManager.persist(association6)
        testEntityManager.persist(association7)

        val pageable = Pageable.unpaged()

        val actual = bookRepository.getBooksByRuleset(
            ruleset = Ruleset(
                allSubRulesets = listOf(SubRuleset(listOf(author1.id)))
            ),
            pageable = pageable,
        )

        assertEquals(1, actual.totalElements)
        assertEquals(book3.id, actual.first()!!.id)
    }


    // This test passes
    @Test
    fun test_multiple_filter() {
        val book1 = Book("Book1")
        val book2 = Book("Book2")
        val book3 = Book("Book3")

        val author1 = Author("Author1")
        val author2 = Author("Author2")
        val author3 = Author("Author3")
        val author4 = Author("Author4")
        val author5 = Author("Author5")

        val association1 = AuthorBookAssociation(author1, book1)
        val association2 = AuthorBookAssociation(author2, book1)

        val association3 = AuthorBookAssociation(author1, book2)
        val association4 = AuthorBookAssociation(author3, book2)

        val association5 = AuthorBookAssociation(author3, book3)
        val association6 = AuthorBookAssociation(author4, book3)
        val association7 = AuthorBookAssociation(author5, book3)

        testEntityManager.persist(book1)
        testEntityManager.persist(book2)
        testEntityManager.persist(book3)
        testEntityManager.persist(author1)
        testEntityManager.persist(author2)
        testEntityManager.persist(author3)
        testEntityManager.persist(author4)
        testEntityManager.persist(author5)
        testEntityManager.persist(association1)
        testEntityManager.persist(association2)
        testEntityManager.persist(association3)
        testEntityManager.persist(association4)
        testEntityManager.persist(association5)
        testEntityManager.persist(association6)
        testEntityManager.persist(association7)

        val pageable = Pageable.unpaged()

        val actual = bookRepository.getBooksByRuleset(
            ruleset = Ruleset(
                allSubRulesets = listOf(
                    SubRuleset(listOf(author1.id)),
                    SubRuleset(listOf(author3.id)),
                ),
            ),
            pageable = pageable,
        )

        assertEquals(2, actual.totalElements)
        assertContentEquals(actual.map { it!!.id }, listOf(book1.id, book3.id))
    }
}
```

**Comment by shouwn** [comment]
안녕하세요. 원인은 Hibernate에서 `NOT ( EXISTS ( ... ) )`를 지원하지 않기 때문으로 보여집니다.
가끔 이런 케이스들이 존재합니다. 예를 들면 `EXIST ( ( ... ) )`도 지원하지 않습니다. 문법적으로는 맞아 보이는데 말이죠. 😢

해결 방법은 쿼리를 수정하는 수밖에 없습니다.
`notExists()`는 동작하기 때문에 `whereOr(notExist(), notExist())` 형태로 쿼리를 수정하는 방식을 말씀드릴 수 있을 것 같습니다.

추후 Predicate 인터페이스에 `isSelfConvertedToNot` 같은 것을 추가해서 `NOT ( EXISTS ( ... ) )` 를 자동으로 `NOT EXISTS ( ... )` 로 변환하는 방법을 강구해보겠습니다.

**Comment by inverseTrig** [comment]
원인에 대한 상세한 설명 감사합니다. 말씀주신 대로 문제를 해결하도록 하겠습니다. 다시 한 번 도움 주셔서 감사합니다.
