### ISSUE TITLE
Spring data jpa v2.5.12 에서 pageable 사용시 런타임 에러가 발생합니다.

### ISSUE THREAD

**Issue by ShindongLee** [line/kotlin-jdsl#760]
Spring Data Jpa 2.5.12 와 KotlinJpqlExecutor의 pageable 기능을 같이 사용하면 런타임에 에러가 발생합니다.

사용중인 버전:
 spring: v2.5.14
 spring-data-jpa: v.2.5.12 (latest of v2.5.x)
 kotlin-jdsl: v3.5.1 (latest)

예시:
```kotlin
val pageable = PageRequest.of(0, 100)
return jpqlExecutor.findAll(pageRequest) {
    select(entity(Something::class))
        .from(entity(Something::class))
        .where( // .. //)
        .orderBy(path(Something::id).asc())
}
```

런타임 에러:

```
Exception in thread “main” java.lang.NoSuchMethodError: ‘void org.springframework.data.jpa.repository.query.StringQuery.<init>(java.lang.String, boolean)’
    at org.springframework.data.jpa.repository.query.QueryEnhancerFactoryAdaptor.forQuery(QueryEnhancerFactoryAdaptor.kt:5)
    at com.linecorp.kotlinjdsl.support.spring.data.jpa.javax.JpqlEntityManagerUtils.createEnhancedQuery(JpqlEntityManagerUtils.kt:68)
    at com.linecorp.kotlinjdsl.support.spring.data.jpa.javax.repository.KotlinJdslJpqlExecutorImpl.createJpaEnhancedQuery(KotlinJdslJpqlExecutorImpl.kt:226)
    at com.linecorp.kotlinjdsl.support.spring.data.jpa.javax.repository.KotlinJdslJpqlExecutorImpl.createList(KotlinJdslJpqlExecutorImpl.kt:272)
    at com.linecorp.kotlinjdsl.support.spring.data.jpa.javax.repository.KotlinJdslJpqlExecutorImpl.findAll(KotlinJdslJpqlExecutorImpl.kt:79)
    at com.linecorp.kotlinjdsl.support.spring.data.jpa.javax.repository.KotlinJdslJpqlExecutorImpl.findAll(KotlinJdslJpqlExecutorImpl.kt:69)
    at com.linecorp.kotlinjdsl.support.spring.data.jpa.javax.repository.KotlinJdslJpqlExecutorImpl$$FastClassBySpringCGLIB$$7df84928.invoke(<generated>)
```

StringQuery에 직접 들어가면 사용중인 버전에서는 아래 함수만 존재합니다.

```java
StringQuery(String query) {

    Assert.hasText(query, “Query must not be null or empty!“);

    this.bindings = new ArrayList<>();
    this.containsPageableInSpel = query.contains(“#pageable”);

    Metadata queryMeta = new Metadata();
    this.query = ParameterBindingParser.INSTANCE.parseParameterBindingsOfQueryIntoBindingsAndReturnCleanedQuery(query,
            this.bindings, queryMeta);

    this.usesJdbcStyleParameters = queryMeta.usesJdbcStyleParameters;
    this.alias = QueryUtils.detectAlias(query);
    this.hasConstructorExpression = QueryUtils.hasConstructorExpression(query);
}
```

Spring 버전을 올리기는 어려운 상황인데, 해결 방법이 있을까요?
그리고 Page 까지는 필요없는 상황에서 v2 처럼 order by 뒤에 limit 을 붙이는 방법은 없을까요?

감사합니다.

**Comment by shouwn** [comment]
ShindongLee 님 안녕하세요. 

먼저 limit의 경우에는 entityManager를 직접 호출하는 방법 밖에는 없습니다.
```kotlin
    fun <T : Any> findAll(
        offset: Int = 0,
        limit: Int = 0,
        select: Jpql.() -> Queryable<SelectQuery<T>>
    ): List<T> {
        val query = jpql(dsl) { select().toQuery() }
        val typedQuery = entityManager.createQuery(query, renderContext)

        if (offset > 0) {
            typedQuery.setFirstResult(offset)
        }

        if (limit > 0) {
            typedQuery.setMaxResults(limit)
        }

        return typedQuery.resultList.filterNotNull()
    }
```

Kotlin JDSL은 EntityManager에 대한 [Extension Function](https://github.com/line/kotlin-jdsl/blob/main/support/spring-data-jpa-javax/src/main/kotlin/com/linecorp/kotlinjdsl/support/spring/data/jpa/javax/extension/EntityManagerExtensions.kt)을 지원하기 때문에 이를 사용해주시면 됩니다.

**Comment by shouwn** [comment]
StringQuery의 경우에는 말씀해주신 것처럼 StringQuery의 인터페이스가 변경되어 Kotlin JDSL이 Spring Boot 2 버전에서 보장하는 버전은 2.7.10입니다. `StringQuery(String query)`가 Spring Boot 2.7.10에서 제거되어 2.7.10으로 버전을 맞추게 되었습니다.

한번 리플렉션을 써서 지원할 수 있는 방법이 있을지 찾아보도록 하겠습니다. 
아마 적용한다면 이번주 주말에 핫픽스로 배포할 수 있을 것 같아요.

하지만 만약 그 전에 빠르게 반영이 필요하시다면 [이전에 말씀드린 것처럼](https://github.com/line/kotlin-jdsl/issues/745#issuecomment-2260002889) `PageableExecutionUtils`을 사용하시는 것을 추천드립니다.

**Comment by ShindongLee** [comment]
친절한 답변 감사드립니다. 🙇‍♂️

**Comment by shouwn** [comment]
@ShindongLee 안녕하세요.
Spring Boot 2.5.X에 Pageable을 지원할 수 있는 방법이 있는지 찾아보았고, 아쉽지만 지원해 드릴 수 없겠다고 결론을 내리게 되었습니다.

StringQuery의 경우는 리플렉션을 이용해 해소했습니다.
하지만 페이지 쿼리를 만들기 위한 Spring의 다른 클래스들이 2.5.X에 없는 것을 확인했습니다.
확인해보니 Spring Data JPA 2.7.X 부터 페이지 쿼리를 만드는 방식이 많이 바뀐 것으로 보입니다.
이로 인해 현재 구현에 2.5.X 호환성 코드를 녹여낼 수 없어 지원해 드릴 수 없겠다고 결론 내리게 되었습니다. 😢 

불편을 드려서 죄송합니다.

**Comment by ShindongLee** [comment]
@shouwn 님 안녕하세요, 확인이 늦었습니다. entityManager 를 직접 사용하는 방법으로 해결해서 문제 없습니다. 

해결 방법을 알아봐주시고, 항상 친절하게 답변주셔서 감사합니다.
